name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # 또는 배포할 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest # self-hosted 러너라면 'self-hosted'로 변경
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby manually
        run: |
          sudo apt update
          sudo apt install -y rbenv ruby-build
          rbenv install 3.1.4
          rbenv global 3.1.4
          echo "PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH" >> $GITHUB_ENV

      - name: Check Ruby version
        run: ruby -v

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
